### ISSUE TITLE
This is not compatible with Apache httpd mod_lua on Win32

### ISSUE THREAD

**Issue by inzi** [harningt/luajson#29]
Of note, enters into a loop of some type when invokes by apache 2.4 httpd mod_lua; causing the server to be unresponsive.

The error is somehow related to the buildDecoder function.

Tested on Win7 64bit, running Apache 2.4 32bit with Lua 5.1.

I have been unable to determine where the problem lies specifically. If I load json.decode and comment out line 117 to read:

--  prebuilt_decoders[_M[mode]] = buildDecoder(_M[mode])

It will load.

If I leave the line uncommented, Apache exits with status 255.

**Comment by harningt** [comment]
Have you tried the latest LuaJSON version?

**Comment by harningt** [comment]
Over a year old, closing out.
