### ISSUE TITLE
flexible mode to replace invalid empty fields with NULL

### ISSUE THREAD

**Issue by fiendish** [harningt/luajson#38]
Some online APIs return invalid JSON with empty array indices. One example (from google translate api) is 

`[[["I am fiendish","je suis fiendish",,,3]],,"fr",,,,0.15691464,,[["fr"],,[0.15691464],["fr"]]]`

The empty array entries are invalid JSON, surely, but it's clear that they are meant to be treated as explicitly null. Any chance this could be handled either seamlessly or with a "flexibly handle empty fields" option on decode?

**Comment by harningt** [comment]
Right now this isn't handled through any option. Thinking this through, how would a trailing comma be handled? Would it cause a final 'null' element to be captured or be ignored.

Right now there is a trailingComma option available that allows a final comma right before ']' and ignores it.

**Comment by fiendish** [comment]
I would say to add a final null unless the trailingComma option is active in which case ignore it. That way you get the full combination of effects.

**Comment by harningt** [comment]
Looks to be all set from my end.
```
local decoder = require("json.decode").getDecoder({ array = { allowEmptyElement = true } })
local result = decoder('[[["I am fiendish","je suis fiendish",,,3]],,"fr",,,,0.15691464,,[["fr"],,[0.15691464],["fr"]]]')
```

Seemed to decode exactly how one would want.

I use 'undefined' as typical JavaScript uses for empty values. However if you have others.allowUndefined = false set, it would use the value for 'null'.

If you want Lua native nil, this decoder would get you want you'd want:
```
local decoder = require("json.decode").getDecoder({ array = { allowEmptyElement = true }, others = { null = false, undefined = false } })
```

If this is all good, I'll be pushing a release very very soon... by the end of the week at latest, or earlier if I see that Lpeg 1.0.1 is uploaded to LuaRocks before then so I can at least tick that off the support list at the same time.

**Comment by harningt** [comment]
LuaJSON release 1.3.4 on is way out with this fix considered complete.
